Skeleton in pybullet: physcap.urdf

Vnet result (on sequence): motion.motion, ddd.mdd

In [1]:
import numpy as np

data_path = 'data/sample_vnect_2ds.npy'

data = np.load(data_path) #(14235, 17, 2)

print(data.shape)

(14235, 17, 2)


In [2]:
data_path = 'data/vnect_motions.npy'

data = np.load(data_path) #(33, 600) #dimension related to dofs

print(data.shape)

(33, 600)


In [3]:
def dof_name_getter(skeleton_filename):
    with open(skeleton_filename) as f:
        content = f.readlines()
    content = np.array([x.strip().split(" ") for x in content], dtype=object)
    dof_names_mess = np.array(content[99:][np.arange(0, len(content[99:]), 3)[:-1]])
    dof_names = [x[0] for x in dof_names_mess]
    return dof_names

skeleton_filename = 'asset/physcap.skeleton'

dof_names = dof_name_getter(skeleton_filename)

print(len(dof_names))
print(dof_names)

33
['trans_root_tx', 'trans_root_ty', 'trans_root_tz', 'rot_root_rx', 'rot_root_ry', 'rot_root_rz', 'rot_left_hip_rx', 'rot_left_hip_ry', 'rot_left_hip_rz', 'rot_right_hip_rx', 'rot_right_hip_ry', 'rot_right_hip_rz', 'rot_left_knee_rx', 'rot_right_knee_rx', 'rot_left_ankle_rx', 'rot_left_ankle_ry', 'rot_right_ankle_rx', 'rot_right_ankle_ry', 'rot_neck_rx', 'rot_neck_ry', 'rot_neck_rz', 'rot_left_clavicle_ry', 'rot_left_clavicle_rz', 'rot_right_clavicle_ry', 'rot_right_clavicle_rz', 'rot_left_shoulder_ry', 'rot_left_shoulder_rz', 'rot_right_shoulder_ry', 'rot_right_shoulder_rz', 'rot_left_elbow_rx', 'rot_left_elbow_ry', 'rot_right_elbow_rx', 'rot_right_elbow_ry']


In [4]:
data_path = 'results/PhyCap_q.npy' #(4792, 43)
# data_path = 'results/VNect_q.npy' #(2408, 43)
# data_path = 'results/pred_con.npy' #(14235, 1, 4)
# data_path = 'results/pred_sta.npy' #(14235, 1)

data = np.load(data_path) #(33, 600) #dimension related to dofs

print(data.shape)

(4792, 43)


In [7]:
import joblib
import os
data_dir = '/home/datassd/yuxuan/data_event_out'
action = 'subject01_group1_time1'
num_frame = len(os.listdir('%s/pose_events/%s' % (data_dir, action))) - 1
theta_list, tran_list, joints2d_list, joints3d_list = [], [], [], []
for idx in range(num_frame):
    beta, theta, tran, joints3d, joints2d = joblib.load(
                '%s/pose_events/%s/pose%04i.pkl' % (data_dir, action, idx))
    theta_list.append(theta)
    tran_list.append(tran)
    joints2d_list.append(joints2d)
    joints3d_list.append(joints3d_list)

In [11]:
kinematic_2d = np.stack(joints2d_list, axis=0)
print(kinematic_2d.shape)
print(kinematic_2d[0,0])

(1345, 24, 3)
[[3.55519741 3.59180427 3.55653177 ... 3.43309809 3.53878823 3.42535081]
 [3.55952256 3.59598563 3.56035521 ... 3.43472488 3.53671354 3.42668185]
 [3.55962225 3.59618792 3.56007234 ... 3.43147463 3.53657321 3.42269672]
 ...
 [3.65166349 3.65201679 3.66931156 ... 3.40050675 3.71064262 3.32857049]
 [3.65680305 3.65489879 3.67655446 ... 3.40580291 3.78338245 3.32961747]
 [3.66094556 3.65862732 3.68600122 ... 3.44589924 3.82421567 3.37110423]]
